### ISSUE TITLE
Doesn't show up in Module Settings tab in worlds created in versions >= 0.7.7

### ISSUE THREAD

**Issue by sharkbruhaha** [KayelGee/moar-folders#1]
Flat out isn't showing for some reason in new worlds since at least 0.7.7

**Comment by sharkbruhaha** [comment]
Erceron#0370 from the foundry server figured it out! Your mod is calling the script when there is an active Scene (on the hook canvasReady ) so in these worlds that I didn't have any open it wasn't actually activating. Might be wise to change that to something that works on world being loaded instead? (sorry not familiar with the api to give a good alternate)

**Comment by KayelGee** [comment]
fixed in 1.0.2

**Comment by sharkbruhaha** [comment]
fixed in recent release
